services:
  psql:
    container_name: monorepo.psql
    image: postgres:15.6-alpine
    restart: always
    ports:
      - "5454:5432"
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localWelcome
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost" ]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - monorepo-data:/var/lib/postgresql/monorepo/data

  gateway:
    container_name: service.gateway
    build:
      context: .
      dockerfile: dockerfiles/local/service.gateway.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - psql

  core:
    container_name: service.core
    build:
      context: .
      dockerfile: dockerfiles/local/service.core.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - psql

volumes:
  monorepo-data:
