name: otos.foundation.Test
run-name: ${{github.actor}} started foundation.Test

on:
    push:
        paths:
            - 'foundation/**'
        branches:
            - '*'

jobs:
    test:
        name: test foundation
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Go Mod Cache
                uses: actions/cache@v4
                with:
                    path: "~/go/pkg/mod"
                    key: ${{ runner.os }}-go-mod-foundation-${{ hashFiles('**/go.sum') }}

            -   name: Test Foundation
                run: make testfoundation
